---
# defaults file for ansible-role-vault-remove

vault_bin_path: "/usr/bin"
vault_conf: "/etc/vault/config.hcl"
vault_certs: "/etc/vault/certs"
vault_user: "vault"
vault_group: "vault"
vault_service: "vault"
vault_profile: "/etc/profile.d/vault.sh"
audit_path: "/var/log/vault"
consul_server_group: "consul_server"
consul_port: 8500
