---
# defaults file for ansible-role-consul-install

consul_version: latest
consul_arch: linux_amd64
checkpoint_url: "https://checkpoint-api.hashicorp.com/v1/check/consul"
consul_dependencies:
  - unzip
consul_bin_path: "/usr/bin"
consul_path: "/var/lib/consul"
consul_conf: "/etc/consul/consul_agent.hcl"
consul_local_script: False
consul_datacenter: "dc1"
consul_base_ip: "10.1.42."
consul_user: "consul"
consul_uid: "8501"
consul_group: "consul"
consul_gid: "8501"
consul_service: "consul"
ansible_consul_group: "consul"
# Following variables only need setting if the consul servers are already up and running
# If this is empty, assume an initial consul service deployment (including servers)
# otherwise use these servers to configure the client agent configuration files
consul_servers: []
# If joining consul clients to existing consul servers, the gossip secret key must be supplied
consul_secret: ""

